# Task types
- name: "type: bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "type: feature"
  color: "1d76db"
  description: "A new feature or capability"

- name: "type: improvement"
  color: "a2eeef"
  description: "Enhancement of an existing feature"

- name: "type: chore"
  color: "cfd3d7"
  description: "Routine maintenance or technical task"

- name: "type: task"
  color: "ededed"
  description: "General task not classified elsewhere"

- name: "type: tests"
  color: "5319e7"
  description: "Tests: unit, integration, or e2e"

- name: "type: docs"
  color: "0075ca"
  description: "Documentation updates or improvements"

# Priority levels
- name: "priority: high"
  color: "e11d21"
  description: "High impact or urgent task"

- name: "priority: medium"
  color: "fbca04"
  description: "Moderate priority task"

- name: "priority: low"
  color: "0e8a16"
  description: "Low priority or non-urgent"

# Status indicators
- name: "status: in progress"
  color: "0052cc"
  description: "Work is currently being done"

- name: "status: blocked"
  color: "d93f0b"
  description: "Blocked by another task or issue"

- name: "status: ready for review"
  color: "5319e7"
  description: "Awaiting code or product review"

- name: "status: done"
  color: "0e8a16"
  description: "Task has been completed"

# Component or scope
- name: "component: frontend"
  color: "f9d0c4"
  description: "Related to the frontend part of the app"

- name: "component: backend"
  color: "c2e0c6"
  description: "Related to the backend/server"

- name: "component: api"
  color: "bfdadc"
  description: "Concerns the API design or behavior"

- name: "component: auth"
  color: "fef2c0"
  description: "Related to authentication/authorization"

# Area labels
- name: "area: java"
  color: "b07219"
  description: "Java-specific code or logic"

- name: "area: config"
  color: "006b75"
  description: "Configuration files or settings (YAML, env, props)"

- name: "area: spring-boot"
  color: "f89c0e"
  description: "Spring Boot-specific components and annotations"

- name: "area: ci/cd"
  color: "0c6e99"
  description: "Continuous Integration / Deployment pipelines"

- name: "area: docker"
  color: "2496ed"
  description: "Dockerfiles, compose files, and container config"
