name: justedlev-microservice
services:
  bridgewayhub:
    container_name: bridgewayhub
    image: justedlev/bridgewayhub:1.0.0
    build:
      context: .
    env_file:
      - ".docker.env"
    ports:
      - 8123:8123
