name: justedlev-microservice
services:
  bridgewayhub:
    container_name: bridgewayhub
    image: justedlev/bridgewayhub:0.0.1-SNAPSHOT
    build:
      context: .
    env_file:
      - docker.env
    ports:
      - 8123:8123
    depends_on:
      - sso
      - service-discovery

# Service discovery
  service-discovery:
    container_name: service-discovery
    image: justedlev/simple-eureka-server:1.0.0-SNAPSHOT
    environment:
      PORT: 8761
      USERNAME: docker
      PASSWORD: docker!123
      SERVICE_DISCOVERY_ZONE: http://service-discovery:${PORT}/eureka
    ports:
      - 8761:8761

  # SSO service (keycloak)
  sso:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    command: ["start-dev", "--http-port=9321"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME: localhost
      KC_DB: keycloak-db
      KC_DB_URL: jdbc:postgresql://postgres:5432/${KC_DB}
      KC_DB_USERNAME: su
      KC_DB_PASSWORD: su
      KC_DB_SCHEMA: keycloak
    depends_on:
      - postgres
    ports:
      - 9321:9321

  # Postgres DB
  postgres:
    container_name: postgres
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: justedlev-db
      POSTGRES_USER: su
      POSTGRES_PASSWORD: su
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 12s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 250MB

volumes:
  db-data:
