name: justedlev-microservice
services:
  bridgewayhub:
    container_name: bridgewayhub
    image: justedlev/bridgewayhub:0.0.1-SNAPSHOT
    build:
      context: .
    env_file:
      - docker.env
    ports:
      - 8123:8123
    depends_on:
      - simple-eureka-server
  sso:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.3
    command: [ "start-dev", "--http-port=9321" ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME: localhost
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/justedlev-hub-db
      KC_DB_USERNAME: justedlev
      KC_DB_PASSWORD: Just96lyk3@d
      KC_DB_SCHEMA: keycloak
    depends_on:
      - postgres
    ports:
      - 9321:9321