name: justedlev-microservice
services:
  bridgewayhub:
    container_name: bridgewayhub
    image: justedlev/bridgewayhub:0.0.1-SNAPSHOT
    build:
      context: .
    env_file:
      - docker.env
    ports:
      - 8123:8123
# Uncomment if keycloak with simple-eureka-server was added
#    depends_on:
#      - sso
#      - simple-eureka-server