name: justedlev-microservice
services:
  server:
    container_name: bridgewayhub
    image: justedlev/bridgewayhub:0.0.1-SNAPSHOT
    build:
      context: .
    env_file:
      - docker.env
    ports:
      - 8123:8123
