server:
  port: ${PORT:8765}
  error:
    include-stacktrace: never

spring:
  config:
    import:
      - classpath:/keycloak.yml
      - classpath:/springdoc.yml
      - classpath:/management.yml
      - classpath:/eureka.yml
      - classpath:/logging.yml
      - classpath:/security.yml
  application:
    name: '@project.name@'
  devtools:
    add-properties: false
    restart:
      enabled: false
  security:
    user:
      name: ${USERNAME:Justedlev}
      password: ${PASSWORD}
      roles: ${ROLES:system}
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}
          jwk-set-uri: ${keycloak.jwk-set-uri}
        opaquetoken:
          introspection-uri: ${keycloak.introspection-uri}
          client-id: ${keycloak.client.id}
          client-secret: ${keycloak.client.secret}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: ${ORIGINS:http://localhost:${server.port},http://localhost:3000}
            allowed-headers: '*'
            allowed-methods: '*'
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: microservice/1
          uri: lb://microservice/1
          predicates:
            - Path=/api/v1/**
        - id: microservice/2
          uri: lb://microservice/2
          predicates:
            - Path=/api/v1/**
